platform :ios, '8.0'
target ‘product-A’ do
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh', '~> 3.1.6'
pod 'AFNetworking', '~> 3.1.0'
pod 'FMDB', '~> 2.6.2'


pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

pod 'ShareSDK3/ShareSDKPlatforms/RenRen'
pod 'ShareSDK3/ShareSDKPlatforms/AliPaySocial'
pod 'ShareSDK3/ShareSDKPlatforms/Kakao'



end


